[tools]
lua="5.4.7"

[tasks.setup]
run="luarocks install --deps-only advent_of_code-0.0-0.rockspec"

[tasks.prepare]
run=""

[tasks.list]
run="lua src/main.lua list"

[tasks.solve]
run="lua src/main.lua solve"
