#!/usr/bin/env bash

set -eo pipefail
IFS=$'\n\t'

REPO=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

cd "$REPO" || exit 1

function show_usage() {
  cat <<EOF
Advent of Code Runner

Usage:
  advent-of-code <puzzle> (--lang <lang>) [...options]
  advent-of-code --setup --lang elixir
  advent-of-code y2015d01p1 --lang rust

Options:
  -h --help         Show this help
  -l --lang=<lang>  Solve the puzzle with language <lang>
  --list            List the available languages or solutions for <lang>
  --new             Create the structure for a new <lang> branch
  --remove          Remove the worktree for the <lang>
  --setup           Setup <lang> for the first time
  --test            Use examples instead of personal puzzle input
EOF
}

function list_languages() {
  # local branches except empty lines and current branch
  local from_local=$(git branch | sed 's/^*//;s/^[[:space:]]*//')
  # remote branches without origin prefix and current branch
  local from_remote=$(git branch --remotes | sed 's/origin\///g;/->/d')
  # capture branch name ([<name>] at the end) from a worktree list
  local from_worktrees=$(git worktree list | sed 's/.*\[\([^]]*\)\].*/\1/')

  echo -e "$from_local\n$from_worktrees\n$from_remote" \
    | grep -vE "main|HEAD" \
    | sed "s/^[[:space:]]*//;" \
    | sort \
    | uniq

  return 0
}

function list_solutions() {
  local language="$1"

  local dir="$REPO/solutions/$language"

  if [[ ! -d "$dir" ]]; then
    echo "There's no solution using $language" >&2
    echo "Consider starting a new one with --new or setup it with --setup" >&2

    return 1
  fi

  cd "$dir" || return 1
  mise run compile > /dev/null || return 1

  ./solver list
}

function create_solver() {
  local language="$1"

  local dir="$REPO/solutions/$language"
  local worktree="$(git worktree list | grep $dir)"

  if [[ ! -d "$dir" ]]; then
    git worktree add --orphan -b "$language" "$dir" > /dev/null

    cd "$dir" || return 1
    touch .mise.toml
    ln -s ../../advent-of-code advent-of-code

    echo "Worktree created at $dir"

    return 0
  elif [[ -n "$worktree" ]]; then
    echo "There's a worktree in the directory already"
    echo ">  ${worktree#$REPO/}"

    return 0
  else
    echo "$dir isn't empty, and there's no worktree for it" >&2

    return 1
  fi
}

function setup_solver() {
  local language="$1"

  local dir="$REPO/solutions/$language"
  if [[ ! -d "$dir" ]]; then
    mkdir -p "solutions"
    git worktree add "$dir" "$language"
  fi

  return 0
}

function find_input() {
  local puzzle="$1"
  local input="$REPO/inputs/$puzzle.txt"

  if [[ ! -r "$input" ]]; then
    alt=$(echo "$puzzle" | sed 's/p[[:digit:]]$//')
    input="$REPO/inputs/$alt.txt"
  fi

  if [[ ! -r "$input" ]]; then
    echo "No input file named $puzzle.txt or $alt.txt found in inputs folder" >&2
    return 1
  fi

  echo "$input"
}

function run_solution() {
  local language="$1"
  local puzzle="$2"

  local input
  if [[ -z "$3" ]]; then
    input=$(cat $(find_input "$puzzle"))
  else
    input="$3"
  fi

  cd "solutions/$language" || return 1
  mise run compile > /dev/null || return 1

  echo "$input" | ./solver exec "$puzzle" 2>/dev/null
}

function run_test_case() {
  local test_case=$(cat -)

  local input=$(echo "$test_case" | yq '.input')
  local expected=$(echo "$test_case" | yq '.output')
  local actual=$(run_solution "$language" "$puzzle" "$input")

  if [[ "$actual" == "$expected" ]]; then
    echo "Test passed!!!"

    return 0
  else
    echo -e "Test failed!!!\n"
    echo -e "Expected: \"\"\"\n$expected\n\"\"\""
    echo -e "Actual: \"\"\"\n$actual\n\"\"\""

    return 1
  fi
}

function run_test() {
  local language="$1"
  local puzzle="$2"

  local tests_file="$REPO/examples/$puzzle.yaml"

  if [[ ! -r "$tests_file" ]]; then
    echo "No example file named $puzzle.yaml in examples folder" >&2
    return 1
  fi

  # transform single test cases into array with `[] + .`
  # then flatten them into lines with `.[]`
  readarray test_cases < <(yq -o=j -I=0 '[] + . | .[]' "$tests_file");
  local length=${#test_cases[@]}

  set +e
  local fail=0
  for i in "${!test_cases[@]}"; do
    echo "${test_cases[$i]}" | run_test_case
    if [[ $? -ne 0 ]]; then
      fail=1
    fi

    if [[ $i -ne $((length - 1)) ]]; then
      echo ""
      echo "++++++++++++++++++++++++++++++"
      echo ""
    fi
  done
  set -e

  return $fail
}

function remove_solver() {
  local language="$1"

  local dir="$REPO/solutions/$language"

  if [[ -d "$dir" ]]; then
    git worktree remove "$dir"
    git branch -d "$language"

    echo "Worktree and branch for $language removed"
    return 0
  else
    echo "There's no worktree for $language" >&2
    return 1
  fi
}

function check_requirements() {
  if ! command -v mise &> /dev/null; then
    echo "mise could not be found" >&2
    return 1
  fi

  if ! command -v yq &> /dev/null; then
    echo -e "yq could not be found" >&2
    return 1
  fi
}

check_requirements || exit 1

# LANGUAGE is not specified to allow for external override
POSITIONAL_ARGS=()
LIST="NO"
TEST="NO"
SETUP="NO"
NEW="NO"
REMOVE="NO"

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      show_usage
      exit 0
      ;;
    -l|--lang)
      LANGUAGE="$2"
      shift
      shift
      ;;
    --list)
      LIST="YES"
      shift
      ;;
    --new)
      NEW="YES"
      shift
      ;;
    --setup)
      SETUP="YES"
      shift
      ;;
    --test)
      TEST="YES"
      shift
      ;;
    --remove)
      REMOVE="YES"
      shift
      ;;
    -*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1")
      shift
      ;;
  esac
done

set -- "${POSITIONAL_ARGS[@]}"

if [[ "$LIST" == "YES" ]]; then
  if [[ -z "$LANGUAGE" ]]; then
    list_languages
    exit $?
  fi

  list_solutions "$LANGUAGE"
  exit $?
fi

if [[ -z "$LANGUAGE" ]]; then
  echo -e "You need to provide which language to use\n" >&2

  show_usage
  exit 1
fi

if [[ "$REMOVE" == "YES" ]]; then
  remove_solver "$LANGUAGE"
  exit $?
fi

if [[ "$NEW" == "YES" ]]; then
  create_solver "$LANGUAGE"
  exit $?
fi

if [[ "$SETUP" == "YES" ]]; then
  setup_solver "$LANGUAGE"
  exit $?
fi

if [[ ! -v 1 ]]; then
  echo -e "You need to provide the puzzle to execute\n" >&2

  show_usage
  exit 1
fi

PUZZLE="$1"

if [[ "$TEST" == "YES" ]]; then
  run_test "$LANGUAGE" "$PUZZLE"
  exit $?
fi

run_solution "$LANGUAGE" "$PUZZLE"
