[workspace]
members = ["bin", "lib"]

[workspace.package]
description = "Solutions for AOC puzzles"
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
lib = { path = "./lib", version = "0.0.0" }
probe = { path = "./probe", version = "0.0.0" }
